# Generated by Django 5.2.14 on 2026-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ncr_pincode_prefixes',
            field=models.CharField(default='11,12,20,30', help_text='Comma-separated pincode prefixes considered NCR for shipping. 11=Delhi, 12=Haryana, 20=UP NCR, 30=Faridabad/Gurgaon', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_ncr_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_other_charge',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
        ),
    ]
