# Generated by Django 5.2.14 on 2026-05-25 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('plan_interest', models.CharField(choices=[('MONTHLY', 'Monthly (₹3,000/month)'), ('YEARLY', 'Yearly (₹35,000/year)'), ('ONE_TIME', 'One-time contribution'), ('UNSURE', 'Not sure yet')], default='UNSURE', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('preferred_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.breed')),
                ('preferred_cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cow')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adoption inquiry',
                'verbose_name_plural': 'Adoption inquiries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HamperInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('occasion', models.CharField(choices=[('WEDDING', 'Wedding'), ('POOJA', 'Pooja / religious occasion'), ('FESTIVAL', 'Festival gifting'), ('CORPORATE', 'Corporate gifting'), ('PERSONAL', 'Personal gift'), ('OTHER', 'Other')], max_length=20)),
                ('budget_range', models.CharField(choices=[('UNDER_2K', 'Under ₹2,000 per hamper'), ('TWO_FIVE', '₹2,000 – ₹5,000'), ('FIVE_TEN', '₹5,000 – ₹10,000'), ('ABOVE_TEN', 'Above ₹10,000')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of hampers needed')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamper inquiry',
                'verbose_name_plural': 'Hamper inquiries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-show')], default='NEW', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('alternate_date', models.DateField(blank=True, null=True)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit booking',
                'verbose_name_plural': 'Visit bookings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WholesaleInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('RESOLVED', 'Resolved'), ('SPAM', 'Spam')], default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('expected_volume', models.CharField(choices=[('SMALL', 'Up to ₹50,000 / month'), ('MEDIUM', '₹50,000 – ₹2,00,000 / month'), ('LARGE', 'Above ₹2,00,000 / month')], max_length=20)),
                ('products_interested', models.CharField(help_text='Free text — products of interest', max_length=500)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wholesale inquiry',
                'verbose_name_plural': 'Wholesale inquiries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
