# Generated by Django 5.2.14 on 2026-05-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('DAILY_ESSENTIALS', 'Daily Essentials'), ('MONTHLY_PANTRY', 'Monthly Pantry'), ('CURATED_BOXES', 'Curated Boxes')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('whats_included', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ONE_TIME', 'One-time')], max_length=20)),
                ('delivery_scope', models.CharField(choices=[('NCR_ONLY', 'NCR only'), ('PAN_INDIA', 'Pan-India')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['tier', 'display_order', 'price'],
            },
        ),
    ]
