# Generated by Django 5.2.14 on 2026-05-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_gst_rate_product_hsn_code'),
        ('subscriptions', '0002_subscriptioninquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='billing_cycle',
            new_name='delivery_frequency',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Customer pays once every N days. 30 for monthly plans, 90 for quarterly, 0 for one-time.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='delivery_lead_days',
            field=models.PositiveIntegerField(default=1, help_text='For pan-India shipping: days between order and delivery. Daily NCR plans use 0.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_self_serve',
            field=models.BooleanField(default=True, help_text="If False, 'Get Started' routes to inquiry form from Phase 5 instead of real signup."),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending first payment'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ENDED', 'Ended')], default='PENDING_PAYMENT', max_length=30)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('paused_until', models.DateField(blank=True, null=True)),
                ('pause_started_at', models.DateField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('shipping_recipient_name', models.CharField(max_length=100)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_line_1', models.CharField(max_length=200)),
                ('shipping_line_2', models.CharField(blank=True, max_length=200)),
                ('shipping_landmark', models.CharField(blank=True, max_length=200)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('delivery_time_slot', models.CharField(choices=[('MORNING', 'Morning (6 AM – 10 AM)'), ('EVENING', 'Evening (5 PM – 8 PM)')], default='MORNING', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('delivery_window', models.CharField(default='MORNING', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('SKIPPED', 'Skipped by customer'), ('PAUSED', 'In pause window'), ('MISSED', 'Missed (not delivered)'), ('REFUNDED', 'Refunded')], default='SCHEDULED', max_length=30)),
                ('shipping_recipient_name', models.CharField(max_length=100)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_line_1', models.CharField(max_length=200)),
                ('shipping_line_2', models.CharField(blank=True, max_length=200)),
                ('shipping_landmark', models.CharField(blank=True, max_length=200)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_by_customer', models.BooleanField(default=False)),
                ('delivery_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['scheduled_date', 'shipping_pincode'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptiondelivery')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('INITIAL', 'Initial signup'), ('RENEWAL', 'Renewal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_delivery', models.DecimalField(decimal_places=2, default=1, help_text='How much of this variant per delivery', max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptionplan')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'ordering': ['plan', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptiondelivery',
            index=models.Index(fields=['scheduled_date', 'status'], name='subscriptio_schedul_601fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiondelivery',
            index=models.Index(fields=['scheduled_date', 'shipping_pincode'], name='subscriptio_schedul_2ca836_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplanitem',
            unique_together={('plan', 'variant')},
        ),
    ]
